USE MASTER; 
GO 
 
IF EXISTS ( 
    SELECT * 
    FROM SYS.DATABASES 
    WHERE NAME = 'dbSistemaDoacao' 
) 
BEGIN 
    ALTER DATABASE dbSistemaDoacao 
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE; 
 
    DROP DATABASE dbSistemaDoacao; 
END 
GO 
 
CREATE DATABASE dbSistemaDoacao; 
GO 
 
USE dbSistemaDoacao; 
GO 
 
 
CREATE TABLE ONG ( 
 
    ID_ONG INT IDENTITY(1,1) PRIMARY KEY, 
 
    DSC_NOME VARCHAR(255) NOT NULL, 
 
    NUM_TELEFONE VARCHAR(15) NOT NULL, 
 
    DSC_EMAIL VARCHAR(100) NOT NULL, 
 
    DSC_ENDERECO VARCHAR(150) NOT NULL, 
 
    NUM_CNPJ CHAR(14) NOT NULL 
 
); 
GO 
 
 
CREATE TABLE ADMIN ( 
 
    ID_ADMIN INT IDENTITY(1,1) PRIMARY KEY, 
 
    ID_ONG INT NOT NULL, 
 
    DSC_NOME VARCHAR(100) NOT NULL, 
 
    DSC_EMAIL VARCHAR(100) NOT NULL, 
 
    DSC_SENHA VARCHAR(255) NOT NULL, 
 
    CONSTRAINT FK_ADMIN_ONG 
    FOREIGN KEY (ID_ONG) 
    REFERENCES ONG(ID_ONG) 
 
); 
GO 
 
 
CREATE TABLE ATENDENTE ( 
 
    ID_ATENDENTE INT IDENTITY(1,1) PRIMARY KEY, 
 
    ID_ONG INT NOT NULL, 
 
    DSC_NOME VARCHAR(100) NOT NULL, 
 
    DSC_EMAIL VARCHAR(100) NOT NULL, 
 
    DSC_SENHA VARCHAR(255) NOT NULL, 
 
    CONSTRAINT FK_ATENDENTE_ONG 
    FOREIGN KEY (ID_ONG) 
    REFERENCES ONG(ID_ONG) 
 
); 
GO 
 
 
CREATE TABLE UF ( 
 
    ID_UF INT IDENTITY(1,1) PRIMARY KEY, 
 
    SIGLA_UF CHAR(2) NOT NULL 
 
); 
GO 
 
 
CREATE TABLE USUARIO ( 
 
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY, 
 
    ID_ADMIN INT NOT NULL, 
 
    ID_ATENDENTE INT NOT NULL, 
 
    ID_UF INT NOT NULL, 
 
    DSC_NOME VARCHAR(100) NOT NULL, 
 
    NUM_CPF CHAR(11) NOT NULL, 
 
    NUM_TELEFONE VARCHAR(15) NOT NULL, 
 
    DSC_EMAIL VARCHAR(100) NULL, 
 
    DSC_ENDERECO VARCHAR(150) NOT NULL, 
 
    DSC_CIDADE VARCHAR(50) NOT NULL, 
 
    DATA_NASCIMENTO DATE NOT NULL, 
 
    CONSTRAINT FK_USUARIO_ADMIN 
    FOREIGN KEY (ID_ADMIN) 
    REFERENCES ADMIN(ID_ADMIN), 
 
    CONSTRAINT FK_USUARIO_ATENDENTE 
    FOREIGN KEY (ID_ATENDENTE) 
    REFERENCES ATENDENTE(ID_ATENDENTE), 
 
    CONSTRAINT FK_USUARIO_UF 
    FOREIGN KEY (ID_UF) 
    REFERENCES UF(ID_UF) 
 
); 
GO 
 
 
CREATE TABLE STATUS ( 
 
    ID_STATUS INT IDENTITY(1,1) PRIMARY KEY, 
 
    DSC_STATUS VARCHAR(50) NOT NULL 
 
); 
GO 
 
 
CREATE TABLE INTERESSE ( 
 
    ID_INTERESSE INT IDENTITY(1,1) PRIMARY KEY, 
 
    ID_USUARIO INT NOT NULL, 
 
    ID_STATUS INT NOT NULL, 
 
    DSC_TIPO VARCHAR(255) NOT NULL, 
 
    DSC_DESCRICAO VARCHAR(255) NULL, 
 
    DATA_REGISTRO DATE NOT NULL, 
 
CONSTRAINT FK_INTERESSE_USUARIO 
FOREIGN KEY (ID_USUARIO) 
REFERENCES USUARIO(ID_USUARIO), 
CONSTRAINT FK_INTERESSE_STATUS 
FOREIGN KEY (ID_STATUS) 
REFERENCES STATUS(ID_STATUS) 
); 
GO