IF DB_ID(N'ProjetoPimMvc') IS NULL
BEGIN
    CREATE DATABASE ProjetoPimMvc;
END
GO

USE ProjetoPimMvc;
GO

IF OBJECT_ID(N'[__EFMigrationsHistory]', N'U') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END
GO

IF OBJECT_ID(N'[ONG]', N'U') IS NULL
BEGIN
    CREATE TABLE [ONG] (
        [ID_ONG] int IDENTITY(1,1) NOT NULL,
        [DSC_NOME] nvarchar(150) NOT NULL,
        [NUM_CNPJ] nvarchar(14) NOT NULL,
        [NUM_TELEFONE] nvarchar(11) NULL,
        [DSC_EMAIL] nvarchar(150) NULL,
        [DSC_ENDERECO] nvarchar(200) NULL,
        CONSTRAINT [PK_ONG] PRIMARY KEY ([ID_ONG])
    );

    CREATE UNIQUE INDEX [IX_ONG_NUM_CNPJ] ON [ONG] ([NUM_CNPJ]);
END
GO

IF OBJECT_ID(N'[STATUS]', N'U') IS NULL
BEGIN
    CREATE TABLE [STATUS] (
        [ID_STATUS] int IDENTITY(1,1) NOT NULL,
        [DSC_STATUS] nvarchar(50) NOT NULL,
        CONSTRAINT [PK_STATUS] PRIMARY KEY ([ID_STATUS])
    );

    CREATE UNIQUE INDEX [IX_STATUS_DSC_STATUS] ON [STATUS] ([DSC_STATUS]);
END
GO

IF OBJECT_ID(N'[UF]', N'U') IS NULL
BEGIN
    CREATE TABLE [UF] (
        [ID_UF] int IDENTITY(1,1) NOT NULL,
        [SIGLA_UF] nvarchar(2) NOT NULL,
        [DSC_NOME] nvarchar(50) NOT NULL,
        CONSTRAINT [PK_UF] PRIMARY KEY ([ID_UF])
    );

    CREATE UNIQUE INDEX [IX_UF_SIGLA_UF] ON [UF] ([SIGLA_UF]);
END
GO

IF OBJECT_ID(N'[ADMIN]', N'U') IS NULL
BEGIN
    CREATE TABLE [ADMIN] (
        [ID_ADMIN] int IDENTITY(1,1) NOT NULL,
        [ID_ONG] int NOT NULL,
        [DSC_SENHA_HASH] nvarchar(256) NOT NULL,
        [DSC_SENHA_SALT] nvarchar(128) NOT NULL,
        [DSC_NOME] nvarchar(100) NOT NULL,
        [DSC_EMAIL] nvarchar(150) NOT NULL,
        [NUM_TELEFONE] nvarchar(11) NULL,
        CONSTRAINT [PK_ADMIN] PRIMARY KEY ([ID_ADMIN]),
        CONSTRAINT [FK_ADMIN_ONG_ID_ONG] FOREIGN KEY ([ID_ONG]) REFERENCES [ONG] ([ID_ONG]) ON DELETE NO ACTION
    );

    CREATE UNIQUE INDEX [IX_ADMIN_DSC_EMAIL] ON [ADMIN] ([DSC_EMAIL]);
    CREATE INDEX [IX_ADMIN_ID_ONG] ON [ADMIN] ([ID_ONG]);
END
GO

IF OBJECT_ID(N'[ATENDENTE]', N'U') IS NULL
BEGIN
    CREATE TABLE [ATENDENTE] (
        [ID_ATENDENTE] int IDENTITY(1,1) NOT NULL,
        [ID_ONG] int NOT NULL,
        [DSC_SENHA_HASH] nvarchar(256) NOT NULL,
        [DSC_SENHA_SALT] nvarchar(128) NOT NULL,
        [DSC_NOME] nvarchar(100) NOT NULL,
        [DSC_EMAIL] nvarchar(150) NOT NULL,
        [NUM_TELEFONE] nvarchar(11) NULL,
        CONSTRAINT [PK_ATENDENTE] PRIMARY KEY ([ID_ATENDENTE]),
        CONSTRAINT [FK_ATENDENTE_ONG_ID_ONG] FOREIGN KEY ([ID_ONG]) REFERENCES [ONG] ([ID_ONG]) ON DELETE NO ACTION
    );

    CREATE UNIQUE INDEX [IX_ATENDENTE_DSC_EMAIL] ON [ATENDENTE] ([DSC_EMAIL]);
    CREATE INDEX [IX_ATENDENTE_ID_ONG] ON [ATENDENTE] ([ID_ONG]);
END
GO

IF OBJECT_ID(N'[USUARIO]', N'U') IS NULL
BEGIN
    CREATE TABLE [USUARIO] (
        [ID_USUARIO] int IDENTITY(1,1) NOT NULL,
        [NUM_CPF] nvarchar(11) NOT NULL,
        [DSC_ENDERECO] nvarchar(200) NOT NULL,
        [DSC_CIDADE] nvarchar(100) NOT NULL,
        [DATA_NASCIMENTO] date NOT NULL,
        [DATA_CADASTRO] datetime2 NOT NULL,
        [DSC_TIPO_PARTICIPACAO] nvarchar(20) NOT NULL,
        [ID_UF] int NOT NULL,
        [DSC_NOME] nvarchar(100) NOT NULL,
        [DSC_EMAIL] nvarchar(150) NULL,
        [NUM_TELEFONE] nvarchar(11) NULL,
        CONSTRAINT [PK_USUARIO] PRIMARY KEY ([ID_USUARIO]),
        CONSTRAINT [FK_USUARIO_UF_ID_UF] FOREIGN KEY ([ID_UF]) REFERENCES [UF] ([ID_UF]) ON DELETE NO ACTION
    );

    CREATE UNIQUE INDEX [IX_USUARIO_NUM_CPF] ON [USUARIO] ([NUM_CPF]);
    CREATE INDEX [IX_USUARIO_ID_UF] ON [USUARIO] ([ID_UF]);
END
GO

IF OBJECT_ID(N'[INTERESSE]', N'U') IS NULL
BEGIN
    CREATE TABLE [INTERESSE] (
        [ID_INTERESSE] int IDENTITY(1,1) NOT NULL,
        [ID_USUARIO] int NOT NULL,
        [DSC_TIPO] nvarchar(20) NOT NULL,
        [DSC_DESCRICAO] nvarchar(500) NOT NULL,
        [ID_STATUS] int NOT NULL,
        [DATA_REGISTRO] datetime2 NOT NULL,
        CONSTRAINT [PK_INTERESSE] PRIMARY KEY ([ID_INTERESSE]),
        CONSTRAINT [FK_INTERESSE_STATUS_ID_STATUS] FOREIGN KEY ([ID_STATUS]) REFERENCES [STATUS] ([ID_STATUS]) ON DELETE NO ACTION,
        CONSTRAINT [FK_INTERESSE_USUARIO_ID_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIO] ([ID_USUARIO]) ON DELETE CASCADE
    );

    CREATE INDEX [IX_INTERESSE_ID_STATUS] ON [INTERESSE] ([ID_STATUS]);
    CREATE INDEX [IX_INTERESSE_ID_USUARIO] ON [INTERESSE] ([ID_USUARIO]);
END
GO

IF NOT EXISTS (SELECT 1 FROM [ONG] WHERE [ID_ONG] = 1)
BEGIN
    SET IDENTITY_INSERT [ONG] ON;
    INSERT INTO [ONG] ([ID_ONG], [DSC_NOME], [NUM_CNPJ], [NUM_TELEFONE], [DSC_EMAIL], [DSC_ENDERECO])
    VALUES (1, N'Conecta++', N'12345678000199', N'11919100860', N'contato@ong.com', N'Rua Gugu, Sao Paulo SP');
    SET IDENTITY_INSERT [ONG] OFF;
END
GO

IF NOT EXISTS (SELECT 1 FROM [STATUS] WHERE [DSC_STATUS] = N'Pendente')
BEGIN
    INSERT INTO [STATUS] ([DSC_STATUS]) VALUES (N'Pendente');
END
IF NOT EXISTS (SELECT 1 FROM [STATUS] WHERE [DSC_STATUS] = N'Concluído')
BEGIN
    INSERT INTO [STATUS] ([DSC_STATUS]) VALUES (N'Concluído');
END
IF NOT EXISTS (SELECT 1 FROM [STATUS] WHERE [DSC_STATUS] = N'Cancelado')
BEGIN
    INSERT INTO [STATUS] ([DSC_STATUS]) VALUES (N'Cancelado');
END
GO

IF NOT EXISTS (SELECT 1 FROM [ADMIN] WHERE [DSC_EMAIL] = N'admin@conecta.com')
BEGIN
    SET IDENTITY_INSERT [ADMIN] ON;
    INSERT INTO [ADMIN] ([ID_ADMIN], [ID_ONG], [DSC_NOME], [DSC_EMAIL], [NUM_TELEFONE], [DSC_SENHA_HASH], [DSC_SENHA_SALT])
    VALUES (1, 1, N'Administrador', N'admin@conecta.com', N'11999999999', N'WFxOGGXQds8tge1Z2whoyAnjWybNL5cxxoZ/LsuraGY=', N'oRpZ5CPbtDjoAVfXNM1vUg==');
    SET IDENTITY_INSERT [ADMIN] OFF;
END
GO

IF NOT EXISTS (SELECT 1 FROM [ATENDENTE] WHERE [DSC_EMAIL] = N'atendente@conecta.com')
BEGIN
    SET IDENTITY_INSERT [ATENDENTE] ON;
    INSERT INTO [ATENDENTE] ([ID_ATENDENTE], [ID_ONG], [DSC_NOME], [DSC_EMAIL], [NUM_TELEFONE], [DSC_SENHA_HASH], [DSC_SENHA_SALT])
    VALUES (1, 1, N'Atendente', N'atendente@conecta.com', N'11988888888', N'OOtdX6jwXh8TZAamGnhtMxPVjtqV864l3u8mev8t6Qw=', N'ZzsWoAWNAzhxJTonpQoz+Q==');
    SET IDENTITY_INSERT [ATENDENTE] OFF;
END
GO

IF NOT EXISTS (SELECT 1 FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20260523200000_InitialCreate')
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260523200000_InitialCreate', N'8.0.11');
END
GO
